x-mosquitto-template: &mosquitto-base
  image: eclipse-mosquitto:latest
  restart: unless-stopped
  networks:
    - futurekawa-network

services:

  mosquitto-bresil:
    <<: *mosquitto-base
    container_name: mosquitto-bresil
    ports:
      - "1883:1883"
    volumes:
      - ./IOT/broker/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./IOT/broker/data/bresil:/mosquitto/data

  mosquitto-equateur:
    <<: *mosquitto-base
    container_name: mosquitto-equateur
    ports:
      - "1884:1883"
    volumes:
      - ./IOT/broker/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./IOT/broker/data/equateur:/mosquitto/data

  mosquitto-colombie:
    <<: *mosquitto-base
    container_name: mosquitto-colombie
    ports:
      - "1885:1883"
    volumes:
      - ./IOT/broker/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./IOT/broker/data/colombie:/mosquitto/data

  postgres-bresil:
    image: postgres:17-alpine
    container_name: postgres-bresil
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT_BR}:5432'
    volumes:
      - postgres_data_bresil:/var/lib/postgresql/data
    networks:
      - futurekawa-network

  postgres-equateur:
    image: postgres:17-alpine
    container_name: postgres-equateur
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT_EC}:5432'
    volumes:
      - postgres_data_equateur:/var/lib/postgresql/data
    networks:
      - futurekawa-network

  postgres-colombie:
    image: postgres:17-alpine
    container_name: postgres-colombie
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT_CO}:5432'
    volumes:
      - postgres_data_colombie:/var/lib/postgresql/data
    networks:
      - futurekawa-network

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    restart: unless-stopped
    ports:
      - '1025:1025' # SMTP
      - '8025:8025' # Web UI
    networks:
      - futurekawa-network

  redis:
    image: redis:7-alpine
    env_file:
      - .env
    ports:
      - '${REDIS_PORT}:6379'
    command: ['redis-server', '--requirepass', '${REDIS_PASSWORD}']
    volumes:
      - redis_data:/data
    networks:
      - futurekawa-network

  country-api-bresil:
    build:
      context: .
      dockerfile: apps/country-api/Dockerfile
    container_name: country-api-bresil
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-bresil:5432/${POSTGRES_DB}?schema=public
      MQTT_HOST: mosquitto-bresil
      MQTT_PORT: 1883
      MAIL_HOST: mailpit
      MAIL_PORT: 1025
      PORT: 3000
    ports:
      - '3000:3000'
    depends_on:
      - postgres-bresil
      - mosquitto-bresil
      - mailpit
    networks:
      - futurekawa-network

  country-api-equateur:
    build:
      context: .
      dockerfile: apps/country-api/Dockerfile
    container_name: country-api-equateur
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-equateur:5432/${POSTGRES_DB}?schema=public
      MQTT_HOST: mosquitto-equateur
      MQTT_PORT: 1883
      MAIL_HOST: mailpit
      MAIL_PORT: 1025
      PORT: 3000
    ports:
      - '3002:3000'
    depends_on:
      - postgres-equateur
      - mosquitto-equateur
      - mailpit
    networks:
      - futurekawa-network

  country-api-colombie:
    build:
      context: .
      dockerfile: apps/country-api/Dockerfile
    container_name: country-api-colombie
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-colombie:5432/${POSTGRES_DB}?schema=public
      MQTT_HOST: mosquitto-colombie
      MQTT_PORT: 1883
      MAIL_HOST: mailpit
      MAIL_PORT: 1025
      PORT: 3000
    ports:
      - '3003:3000'
    depends_on:
      - postgres-colombie
      - mosquitto-colombie
      - mailpit
    networks:
      - futurekawa-network

  alerting-bresil:
    build:
      context: .
      dockerfile: apps/alerting-service/Dockerfile
    container_name: alerting-bresil
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-bresil:5432/${POSTGRES_DB}?schema=public
      MQTT_HOST: mosquitto-bresil
      MQTT_PORT: 1883
      MAIL_HOST: mailpit
      MAIL_PORT: 1025
    depends_on:
      - postgres-bresil
      - mosquitto-bresil
      - mailpit
    networks:
      - futurekawa-network

  alerting-equateur:
    build:
      context: .
      dockerfile: apps/alerting-service/Dockerfile
    container_name: alerting-equateur
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-equateur:5432/${POSTGRES_DB}?schema=public
      MQTT_HOST: mosquitto-equateur
      MQTT_PORT: 1883
      MAIL_HOST: mailpit
      MAIL_PORT: 1025
    depends_on:
      - postgres-equateur
      - mosquitto-equateur
      - mailpit
    networks:
      - futurekawa-network

  alerting-colombie:
    build:
      context: .
      dockerfile: apps/alerting-service/Dockerfile
    container_name: alerting-colombie
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-colombie:5432/${POSTGRES_DB}?schema=public
      MQTT_HOST: mosquitto-colombie
      MQTT_PORT: 1883
      MAIL_HOST: mailpit
      MAIL_PORT: 1025
    depends_on:
      - postgres-colombie
      - mosquitto-colombie
      - mailpit
    networks:
      - futurekawa-network

  gateway:
    build:
      context: .
      dockerfile: apps/gateway/Dockerfile
    container_name: gateway
    restart: unless-stopped
    env_file:
      - .env
    environment:
      BRAZIL_API_URL: http://country-api-bresil:3000
      ECUADOR_API_URL: http://country-api-equateur:3000
      COLOMBIA_API_URL: http://country-api-colombie:3000
      GATEWAY_PORT: 3010
    ports:
      - '${GATEWAY_PORT}:3010'
    depends_on:
      - country-api-bresil
      - country-api-equateur
      - country-api-colombie
    networks:
      - futurekawa-network

volumes:
  postgres_data_bresil:
  postgres_data_equateur:
  postgres_data_colombie:
  redis_data:

networks:
  futurekawa-network:
    driver: bridge
