version: '3.8'

x-mosquitto-template: &mosquitto-base
  image: eclipse-mosquitto:latest
  restart: unless-stopped
  volumes:
    - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
  networks:
    - futurekawa-network

services:
  mosquitto-bresil:
    <<: *mosquitto-base
    container-name: mosquitto-bresil
    ports:
      - "1883:1883"
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./data/bresil:/mosquitto/data

  mosquitto-equateur:
    <<: *mosquitto-base
    container_name: mosquitto-equateur
    ports:
      - "1884:1883"
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./data/equateur:/mosquitto/data

  mosquitto-colombie:
    <<: *mosquitto-base
    container_name: mosquitto-colombie
    ports:
      - "1885:1883"
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./data/colombie:/mosquitto/data

networks:
  futurekawa-network: 
    driver: bridge